services:
  store-discovery-service:
    build: ./discovery_service
    container_name: store-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      retries: 4
  store-config-service:
    build: ./config_service
    container_name: store-config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health"]
      interval: 10s
      retries: 10
    environment:
      - DISCOVERY_SERVICE_URL=http://store-discovery-service:8761/eureka
    depends_on:
      store-discovery-service:
        condition: service_healthy
  store-produit-service:
    build: ./produit_service
    container_name: store-produit-service
    ports:
      - '8080:8080'
    expose:
      - '8080'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      retries: 10
    environment:
      - DISCOVERY_SERVICE_URL=http://store-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://store-config-service:9999
    depends_on:
      store-config-service:
        condition: service_healthy
  store-acheteur-service:
    build: ./acheteur_service
    container_name: store-acheteur-service
    ports:
      - '8081:8081'
    expose:
      - '8081'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      retries: 10
    environment:
      - DISCOVERY_SERVICE_URL=http://store-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://store-config-service:9999
    depends_on:
      store-produit-service:
        condition: service_healthy
  store-vente-service:
    build: ./vente_service
    container_name: store-vente-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    environment:
      - DISCOVERY_SERVICE_URL=http://store-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://store-config-service:9999
    depends_on:
      store-acheteur-service:
        condition: service_healthy
  store-gateway-service:
    build: ./gateway_service
    container_name: store-gateway-service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    environment:
      - DISCOVERY_SERVICE_URL=http://store-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://store-config-service:9999
    depends_on:
      store-config-service:
        condition: service_healthy
  front-send-angular:
    build: ./angular-front-end
    container_name: front-send-angular
    ports:
      - '84:80'
    expose:
      - '80'